### ISSUE TITLE
File upload, how to better implement it? 

### ISSUE THREAD

**Issue by Gytjarek** [robmarshall/next-gravity-forms#25]
@robmarshall Hi! I'm going to work on the file upload functionality and am thinking about the best approach for implementing it. So far, I've identified the following issues:

1. This plugin should be installed to enable file uploading: https://github.com/dre1080/wp-graphql-upload. If it's not installed, and we still render a field with its functionality, users might encounter unclear errors. How can we ensure it is required to be installed?
2. Currently, Gravity Forms doesn't immediately throw an error when a user tries to upload a file with an unsupported type. We can easily improve this in our package by throwing the error right away. Do you think it's worth doing, or should we replicate Gravity Forms' functionality as closely as possible?
3. It is possible to enable a multi-file upload option, which activates a dropzone field. I notice that files get uploaded directly to the server on drop. Do you think we should replicate this behavior, or could we submit all files on form submission?

**Comment by Gytjarek** [comment]
@robmarshall do you have any input on above questions?

**Comment by robmarshall** [comment]
Nice one digging into this @Gytjarek 

**How can we ensure it is required to be installed**

We can't. As we are not creating a WordPress side plugin we cannot show any notifications on the admin side.

There is a chance we would be able to check for the existance of a dedicated WpGraphQL Upload field. If there isnt one throw an error.
But tbh I am most inclined to have details of this in the Readme and leave it at that.

**Tries to upload unsupported type**

What happens if a user has added custom support for a file in WP. Such as SVG support, do they also have to handle this within this package?

Maybe we fall back to default WordPress types and show an error as you suggest, and allow this to be overridden by custom types. Purely file extension checking - nothing fancier otherwise it gets a bit scope creepy.

**Multi-file upload**

Thoughts on getting a single file upload working first? Reduce the workload, focus on initial feature and then extend to multi-file later.

**Comment by rossjcoop** [comment]
> yes thanks for your inputs. I've implemented a single file upload already, that's why asking about Multi-file upload :)

Hi @Gytjarek, can you share how you implemented single file upload?

**Comment by Gytjarek** [comment]
> > yes thanks for your inputs. I've implemented a single file upload already, that's why asking about Multi-file upload :)
> 
> Hi @Gytjarek, can you share how you implemented single file upload?

Hi! Pls check it here: https://github.com/Hike-Digital/next-gravity-forms/tree/feature/fileupload, it’s a branch we’re going to merge soon

**Comment by rossjcoop** [comment]
> > > yes thanks for your inputs. I've implemented a single file upload already, that's why asking about Multi-file upload :)
> > 
> > 
> > Hi @Gytjarek, can you share how you implemented single file upload?
> 
> Hi! Pls check it here: https://github.com/Hike-Digital/next-gravity-forms/tree/feature/fileupload, it’s a branch we’re going to merge soon

@Gytjarek Great! Thank you.

**Comment by codilechasseur** [comment]
@Gytjarek Is there a way to switch to the fileupload branch in your fork so I can test?

**Comment by Gytjarek** [comment]
its being implemented
